/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as NewRouteImport } from "./routes/new";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EditSlugRouteImport } from "./routes/edit.$slug";
import { Route as ApiOgpRouteImport } from "./routes/api/ogp";

const NewRoute = NewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EditSlugRoute = EditSlugRouteImport.update({
  id: "/edit/$slug",
  path: "/edit/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiOgpRoute = ApiOgpRouteImport.update({
  id: "/api/ogp",
  path: "/api/ogp",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/api/ogp": typeof ApiOgpRoute;
  "/edit/$slug": typeof EditSlugRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/api/ogp": typeof ApiOgpRoute;
  "/edit/$slug": typeof EditSlugRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/new": typeof NewRoute;
  "/api/ogp": typeof ApiOgpRoute;
  "/edit/$slug": typeof EditSlugRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/new" | "/api/ogp" | "/edit/$slug";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/new" | "/api/ogp" | "/edit/$slug";
  id: "__root__" | "/" | "/new" | "/api/ogp" | "/edit/$slug";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  NewRoute: typeof NewRoute;
  ApiOgpRoute: typeof ApiOgpRoute;
  EditSlugRoute: typeof EditSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/new": {
      id: "/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof NewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/edit/$slug": {
      id: "/edit/$slug";
      path: "/edit/$slug";
      fullPath: "/edit/$slug";
      preLoaderRoute: typeof EditSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/ogp": {
      id: "/api/ogp";
      path: "/api/ogp";
      fullPath: "/api/ogp";
      preLoaderRoute: typeof ApiOgpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ApiOgpRoute: ApiOgpRoute,
  EditSlugRoute: EditSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
