#!/usr/bin/env sh
set -e

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "devel" ]; then
  echo "Direct push to '$branch' is forbidden. Use a pull request."
  exit 1
fi

pnpm turbo typecheck
