[settings]
idiomatic_version_file_enable_tools = ["node"]

[tasks."setup"]
depends = ["setup:deps", "setup:config"]

[tasks."setup:deps"]
run = ["pnpm install"]

[tasks."setup:config"]
run = ["pnpm lefthook install"]