// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/mimifuwacc/api/internal/graphql/models"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	BlogPost struct {
		Content     func(childComplexity int) int
		ContentHash func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		Date        func(childComplexity int) int
		Draft       func(childComplexity int) int
		Excerpt     func(childComplexity int) int
		ID          func(childComplexity int) int
		R2Key       func(childComplexity int) int
		Slug        func(childComplexity int) int
		Tags        func(childComplexity int) int
		Title       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	BlogPostConnection struct {
		Edges    func(childComplexity int) int
		PageInfo func(childComplexity int) int
	}

	BlogPostEdge struct {
		Cursor func(childComplexity int) int
		Node   func(childComplexity int) int
	}

	Mutation struct {
		ArchiveBlogPost func(childComplexity int, slug string) int
		CreateBlogPost  func(childComplexity int, input models.CreateBlogPostInput) int
		DeleteBlogPost  func(childComplexity int, slug string) int
		UpdateBlogPost  func(childComplexity int, input models.UpdateBlogPostInput) int
	}

	MutationResponse struct {
		BlogPost func(childComplexity int) int
		Message  func(childComplexity int) int
		Success  func(childComplexity int) int
	}

	PageInfo struct {
		EndCursor       func(childComplexity int) int
		HasNextPage     func(childComplexity int) int
		HasPreviousPage func(childComplexity int) int
		StartCursor     func(childComplexity int) int
		TotalCount      func(childComplexity int) int
	}

	Query struct {
		BlogPost  func(childComplexity int, slug string) int
		BlogPosts func(childComplexity int, filter *models.BlogPostFilter, page *models.PageInput) int
		Tags      func(childComplexity int) int
	}

	Tag struct {
		ID   func(childComplexity int) int
		Name func(childComplexity int) int
	}
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "BlogPost.content":
		if e.ComplexityRoot.BlogPost.Content == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Content(childComplexity), true

	case "BlogPost.contentHash":
		if e.ComplexityRoot.BlogPost.ContentHash == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.ContentHash(childComplexity), true

	case "BlogPost.createdAt":
		if e.ComplexityRoot.BlogPost.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.CreatedAt(childComplexity), true

	case "BlogPost.date":
		if e.ComplexityRoot.BlogPost.Date == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Date(childComplexity), true

	case "BlogPost.draft":
		if e.ComplexityRoot.BlogPost.Draft == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Draft(childComplexity), true

	case "BlogPost.excerpt":
		if e.ComplexityRoot.BlogPost.Excerpt == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Excerpt(childComplexity), true

	case "BlogPost.id":
		if e.ComplexityRoot.BlogPost.ID == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.ID(childComplexity), true

	case "BlogPost.r2Key":
		if e.ComplexityRoot.BlogPost.R2Key == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.R2Key(childComplexity), true

	case "BlogPost.slug":
		if e.ComplexityRoot.BlogPost.Slug == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Slug(childComplexity), true

	case "BlogPost.tags":
		if e.ComplexityRoot.BlogPost.Tags == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Tags(childComplexity), true

	case "BlogPost.title":
		if e.ComplexityRoot.BlogPost.Title == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.Title(childComplexity), true

	case "BlogPost.updatedAt":
		if e.ComplexityRoot.BlogPost.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.BlogPost.UpdatedAt(childComplexity), true

	case "BlogPostConnection.edges":
		if e.ComplexityRoot.BlogPostConnection.Edges == nil {
			break
		}

		return e.ComplexityRoot.BlogPostConnection.Edges(childComplexity), true

	case "BlogPostConnection.pageInfo":
		if e.ComplexityRoot.BlogPostConnection.PageInfo == nil {
			break
		}

		return e.ComplexityRoot.BlogPostConnection.PageInfo(childComplexity), true

	case "BlogPostEdge.cursor":
		if e.ComplexityRoot.BlogPostEdge.Cursor == nil {
			break
		}

		return e.ComplexityRoot.BlogPostEdge.Cursor(childComplexity), true

	case "BlogPostEdge.node":
		if e.ComplexityRoot.BlogPostEdge.Node == nil {
			break
		}

		return e.ComplexityRoot.BlogPostEdge.Node(childComplexity), true

	case "Mutation.archiveBlogPost":
		if e.ComplexityRoot.Mutation.ArchiveBlogPost == nil {
			break
		}

		args, err := ec.field_Mutation_archiveBlogPost_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.ArchiveBlogPost(childComplexity, args["slug"].(string)), true

	case "Mutation.createBlogPost":
		if e.ComplexityRoot.Mutation.CreateBlogPost == nil {
			break
		}

		args, err := ec.field_Mutation_createBlogPost_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateBlogPost(childComplexity, args["input"].(models.CreateBlogPostInput)), true

	case "Mutation.deleteBlogPost":
		if e.ComplexityRoot.Mutation.DeleteBlogPost == nil {
			break
		}

		args, err := ec.field_Mutation_deleteBlogPost_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.DeleteBlogPost(childComplexity, args["slug"].(string)), true

	case "Mutation.updateBlogPost":
		if e.ComplexityRoot.Mutation.UpdateBlogPost == nil {
			break
		}

		args, err := ec.field_Mutation_updateBlogPost_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateBlogPost(childComplexity, args["input"].(models.UpdateBlogPostInput)), true

	case "MutationResponse.blogPost":
		if e.ComplexityRoot.MutationResponse.BlogPost == nil {
			break
		}

		return e.ComplexityRoot.MutationResponse.BlogPost(childComplexity), true

	case "MutationResponse.message":
		if e.ComplexityRoot.MutationResponse.Message == nil {
			break
		}

		return e.ComplexityRoot.MutationResponse.Message(childComplexity), true

	case "MutationResponse.success":
		if e.ComplexityRoot.MutationResponse.Success == nil {
			break
		}

		return e.ComplexityRoot.MutationResponse.Success(childComplexity), true

	case "PageInfo.endCursor":
		if e.ComplexityRoot.PageInfo.EndCursor == nil {
			break
		}

		return e.ComplexityRoot.PageInfo.EndCursor(childComplexity), true

	case "PageInfo.hasNextPage":
		if e.ComplexityRoot.PageInfo.HasNextPage == nil {
			break
		}

		return e.ComplexityRoot.PageInfo.HasNextPage(childComplexity), true

	case "PageInfo.hasPreviousPage":
		if e.ComplexityRoot.PageInfo.HasPreviousPage == nil {
			break
		}

		return e.ComplexityRoot.PageInfo.HasPreviousPage(childComplexity), true

	case "PageInfo.startCursor":
		if e.ComplexityRoot.PageInfo.StartCursor == nil {
			break
		}

		return e.ComplexityRoot.PageInfo.StartCursor(childComplexity), true

	case "PageInfo.totalCount":
		if e.ComplexityRoot.PageInfo.TotalCount == nil {
			break
		}

		return e.ComplexityRoot.PageInfo.TotalCount(childComplexity), true

	case "Query.blogPost":
		if e.ComplexityRoot.Query.BlogPost == nil {
			break
		}

		args, err := ec.field_Query_blogPost_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.BlogPost(childComplexity, args["slug"].(string)), true

	case "Query.blogPosts":
		if e.ComplexityRoot.Query.BlogPosts == nil {
			break
		}

		args, err := ec.field_Query_blogPosts_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.BlogPosts(childComplexity, args["filter"].(*models.BlogPostFilter), args["page"].(*models.PageInput)), true

	case "Query.tags":
		if e.ComplexityRoot.Query.Tags == nil {
			break
		}

		return e.ComplexityRoot.Query.Tags(childComplexity), true

	case "Tag.id":
		if e.ComplexityRoot.Tag.ID == nil {
			break
		}

		return e.ComplexityRoot.Tag.ID(childComplexity), true

	case "Tag.name":
		if e.ComplexityRoot.Tag.Name == nil {
			break
		}

		return e.ComplexityRoot.Tag.Name(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputBlogPostFilter,
		ec.unmarshalInputCreateBlogPostInput,
		ec.unmarshalInputPageInput,
		ec.unmarshalInputUpdateBlogPostInput,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) executionContext {
	return executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

//go:embed "schema.graphql"
var sourcesFS embed.FS

func sourceData(filename string) string {
	data, err := sourcesFS.ReadFile(filename)
	if err != nil {
		panic(fmt.Sprintf("codegen problem: %s not available", filename))
	}
	return string(data)
}

var sources = []*ast.Source{
	{Name: "schema.graphql", Input: sourceData("schema.graphql"), BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
