package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"

	"github.com/mimifuwacc/api/internal/entity"
	"github.com/mimifuwacc/api/internal/graphql/cursor"
	"github.com/mimifuwacc/api/internal/graphql/models"
	"github.com/mimifuwacc/api/internal/repository"
)

// CreateBlogPost is the resolver for the createBlogPost field.
func (r *mutationResolver) CreateBlogPost(ctx context.Context, input models.CreateBlogPostInput) (*models.MutationResponse, error) {
	if r.BlogPostRepo == nil {
		return &models.MutationResponse{
			Success: false,
			Message: "blog post repository not configured",
		}, fmt.Errorf("repository not configured")
	}

	// Convert input to entity
	draft := false
	if input.Draft != nil {
		draft = *input.Draft
	}

	post := &entity.BlogPost{
		Slug:    input.Slug,
		R2Key:   fmt.Sprintf("posts/%s.md", input.Slug),
		Title:   input.Title,
		Excerpt: input.Excerpt,
		Content: input.Content,
		Date:    input.Date.ToTime(),
		Tags:    input.Tags,
		Draft:   draft,
	}

	// Upload content to R2
	if r.StorageRepo != nil {
		content := []byte(input.Content)
		if err := r.StorageRepo.Upload(ctx, post.R2Key, content, "text/markdown"); err != nil {
			return &models.MutationResponse{
				Success: false,
				Message: fmt.Sprintf("failed to upload content: %v", err),
			}, err
		}
	}

	// Upsert to D1
	if err := r.BlogPostRepo.Upsert(ctx, post); err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("failed to create blog post: %v", err),
		}, err
	}

	// Handle tags
	if r.TagRepo != nil {
		postID, err := r.BlogPostRepo.GetIDBySlug(ctx, post.Slug)
		if err != nil {
			return &models.MutationResponse{
				Success: false,
				Message: fmt.Sprintf("failed to get blog post ID: %v", err),
			}, err
		}

		// Delete existing tags
		r.BlogPostRepo.DeleteTags(ctx, postID)

		// Create and link tags
		for _, tagName := range input.Tags {
			tag, err := r.TagRepo.FindOrCreate(ctx, tagName)
			if err != nil {
				continue // Skip tags that fail to create
			}
			r.TagRepo.LinkToBlogPost(ctx, postID, tag.ID)
		}
	}

	// Fetch the created post with tags
	createdPost, err := r.BlogPostRepo.FindBySlugWithTags(ctx, post.Slug)
	if err != nil {
		return &models.MutationResponse{
			Success: true,
			Message: "Blog post created but failed to fetch",
		}, nil
	}

	return &models.MutationResponse{
		Success:  true,
		Message:  "Blog post created successfully",
		BlogPost: entityToModelPost(createdPost),
	}, nil
}

// UpdateBlogPost is the resolver for the updateBlogPost field.
func (r *mutationResolver) UpdateBlogPost(ctx context.Context, input models.UpdateBlogPostInput) (*models.MutationResponse, error) {
	if r.BlogPostRepo == nil {
		return &models.MutationResponse{
			Success: false,
			Message: "blog post repository not configured",
		}, fmt.Errorf("repository not configured")
	}

	// Find existing post
	post, err := r.BlogPostRepo.FindBySlugWithTags(ctx, input.Slug)
	if err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("blog post not found: %v", err),
		}, err
	}

	// Update fields if provided
	if input.Title != nil {
		post.Title = *input.Title
	}
	if input.Excerpt != nil {
		post.Excerpt = *input.Excerpt
	}
	if input.Content != nil {
		post.Content = *input.Content
	}
	if input.Date != nil {
		post.Date = input.Date.ToTime()
	}
	if input.Draft != nil {
		post.Draft = *input.Draft
	}
	if input.Tags != nil {
		post.Tags = input.Tags
	}

	// Upload content to R2 if updated
	if input.Content != nil && r.StorageRepo != nil {
		content := []byte(*input.Content)
		if err := r.StorageRepo.Upload(ctx, post.R2Key, content, "text/markdown"); err != nil {
			return &models.MutationResponse{
				Success: false,
				Message: fmt.Sprintf("failed to upload content: %v", err),
			}, err
		}
	}

	// Update in D1
	if err := r.BlogPostRepo.Upsert(ctx, post); err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("failed to update blog post: %v", err),
		}, err
	}

	// Update tags if provided
	if input.Tags != nil && r.TagRepo != nil {
		postID, err := r.BlogPostRepo.GetIDBySlug(ctx, post.Slug)
		if err == nil {
			// Delete existing tags
			r.BlogPostRepo.DeleteTags(ctx, postID)

			// Create and link new tags
			for _, tagName := range input.Tags {
				tag, err := r.TagRepo.FindOrCreate(ctx, tagName)
				if err != nil {
					continue
				}
				r.TagRepo.LinkToBlogPost(ctx, postID, tag.ID)
			}
		}
	}

	// Fetch the updated post
	updatedPost, err := r.BlogPostRepo.FindBySlugWithTags(ctx, post.Slug)
	if err != nil {
		return &models.MutationResponse{
			Success: true,
			Message: "Blog post updated but failed to fetch",
		}, nil
	}

	return &models.MutationResponse{
		Success:  true,
		Message:  "Blog post updated successfully",
		BlogPost: entityToModelPost(updatedPost),
	}, nil
}

// DeleteBlogPost is the resolver for the deleteBlogPost field.
func (r *mutationResolver) DeleteBlogPost(ctx context.Context, slug string) (*models.MutationResponse, error) {
	if r.BlogPostRepo == nil {
		return &models.MutationResponse{
			Success: false,
			Message: "blog post repository not configured",
		}, fmt.Errorf("repository not configured")
	}

	// Find post to get R2 key
	post, err := r.BlogPostRepo.FindBySlug(ctx, slug)
	if err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("blog post not found: %v", err),
		}, err
	}

	// Delete from R2
	if r.StorageRepo != nil {
		if err := r.StorageRepo.Delete(ctx, post.R2Key); err != nil {
			// Continue with D1 deletion even if R2 fails
			fmt.Printf("warning: failed to delete from R2: %v\n", err)
		}
	}

	// Delete from D1
	if err := r.BlogPostRepo.Delete(ctx, slug); err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("failed to delete blog post: %v", err),
		}, err
	}

	return &models.MutationResponse{
		Success: true,
		Message: "Blog post deleted successfully",
	}, nil
}

// ArchiveBlogPost is the resolver for the archiveBlogPost field.
func (r *mutationResolver) ArchiveBlogPost(ctx context.Context, slug string) (*models.MutationResponse, error) {
	if r.BlogPostRepo == nil {
		return &models.MutationResponse{
			Success: false,
			Message: "blog post repository not configured",
		}, fmt.Errorf("repository not configured")
	}

	// Set draft to true
	if err := r.BlogPostRepo.UpdateDraftStatus(ctx, slug, true); err != nil {
		return &models.MutationResponse{
			Success: false,
			Message: fmt.Sprintf("failed to archive blog post: %v", err),
		}, err
	}

	// Fetch the archived post
	archivedPost, err := r.BlogPostRepo.FindBySlugWithTags(ctx, slug)
	if err != nil {
		return &models.MutationResponse{
			Success: true,
			Message: "Blog post archived",
		}, nil
	}

	return &models.MutationResponse{
		Success:  true,
		Message:  "Blog post archived successfully",
		BlogPost: entityToModelPost(archivedPost),
	}, nil
}

// BlogPost is the resolver for the blogPost field.
func (r *queryResolver) BlogPost(ctx context.Context, slug string) (*models.BlogPost, error) {
	if r.BlogPostRepo == nil {
		return nil, fmt.Errorf("blog post repository not configured")
	}

	post, err := r.BlogPostRepo.FindBySlugWithTags(ctx, slug)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch blog post: %w", err)
	}

	return entityToModelPost(post), nil
}

// BlogPosts is the resolver for the blogPosts field.
func (r *queryResolver) BlogPosts(ctx context.Context, filter *models.BlogPostFilter, page *models.PageInput) (*models.BlogPostConnection, error) {
	if r.BlogPostRepo == nil {
		return nil, fmt.Errorf("blog post repository not configured")
	}

	// Convert filter
	repoFilter := repository.BlogPostFilter{}
	if filter != nil {
		repoFilter.Draft = filter.Draft
		repoFilter.TagName = filter.Tag
		repoFilter.SearchTerm = filter.Search
		if filter.DateAfter != nil {
			t := filter.DateAfter.ToTime()
			repoFilter.DateAfter = &t
		}
		if filter.DateBefore != nil {
			t := filter.DateBefore.ToTime()
			repoFilter.DateBefore = &t
		}
	}

	// Convert pagination
	first := 20
	if page != nil && page.First != nil {
		first = *page.First
	}

	// Calculate offset from cursor
	offset := 0
	if page != nil && page.After != nil {
		// For now, we'll use a simple offset-based approach
		// TODO: Implement proper cursor-based pagination
		offset = 0 // Would decode cursor here
	}

	repoPagination := repository.Pagination{
		Limit:  first,
		Offset: offset,
	}

	// Fetch posts and count
	posts, err := r.BlogPostRepo.FindWithPagination(ctx, repoFilter, repoPagination)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch blog posts: %w", err)
	}

	totalCount, err := r.BlogPostRepo.Count(ctx, repoFilter)
	if err != nil {
		return nil, fmt.Errorf("failed to count blog posts: %w", err)
	}

	// Build edges
	edges := make([]*models.BlogPostEdge, len(posts))
	for i, post := range posts {
		edges[i] = &models.BlogPostEdge{
			Node:   entityToModelPost(post),
			Cursor: cursor.Cursor{ID: post.ID, Created: post.CreatedAt},
		}
	}

	// Build page info
	hasNextPage := int64(offset+len(posts)) < totalCount
	startCursor := (*cursor.Cursor)(nil)
	endCursor := (*cursor.Cursor)(nil)
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &models.BlogPostConnection{
		Edges: edges,
		PageInfo: &models.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: offset > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
			TotalCount:      int(totalCount),
		},
	}, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*models.Tag, error) {
	if r.BlogPostRepo == nil {
		return nil, fmt.Errorf("blog post repository not configured")
	}

	// Type assert to get access to FindAllTags method
	type TagsGetter interface {
		FindAllTags(ctx context.Context, limit int) ([]*entity.Tag, error)
	}

	tagsGetter, ok := r.BlogPostRepo.(TagsGetter)
	if !ok {
		return nil, fmt.Errorf("blog post repository does not support listing tags")
	}

	tags, err := tagsGetter.FindAllTags(ctx, 1000)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch tags: %w", err)
	}

	result := make([]*models.Tag, len(tags))
	for i, tag := range tags {
		result[i] = &models.Tag{
			ID:   strconv.FormatInt(tag.ID, 10),
			Name: tag.Name,
		}
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func entityToModelPost(post *entity.BlogPost) *models.BlogPost {
	tags := make([]*models.Tag, len(post.Tags))
	for i, tagName := range post.Tags {
		tags[i] = &models.Tag{
			ID:   "", // Tags don't have IDs in the entity
			Name: tagName,
		}
	}

	var contentHash *string
	if post.ContentHash != "" {
		contentHash = &post.ContentHash
	}

	return &models.BlogPost{
		ID:          strconv.FormatInt(post.ID, 10),
		Slug:        post.Slug,
		R2Key:       post.R2Key,
		Title:       post.Title,
		Excerpt:     post.Excerpt,
		Content:     post.Content, // Will be loaded from R2 if empty
		Date:        scalar.FromTime(post.Date),
		Tags:        tags,
		Draft:       post.Draft,
		ContentHash: contentHash,
		CreatedAt:   scalar.FromTime(post.CreatedAt),
		UpdatedAt:   scalar.FromTime(post.UpdatedAt),
	}
}
*/
