// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/mimifuwacc/api/internal/graphql/cursor"
	"github.com/mimifuwacc/api/internal/graphql/scalar"
)

type BlogPost struct {
	ID          string      `json:"id"`
	Slug        string      `json:"slug"`
	R2Key       string      `json:"r2Key"`
	Title       string      `json:"title"`
	Excerpt     string      `json:"excerpt"`
	Content     string      `json:"content"`
	Date        scalar.Time `json:"date"`
	Tags        []*Tag      `json:"tags"`
	Draft       bool        `json:"draft"`
	ContentHash *string     `json:"contentHash,omitempty"`
	CreatedAt   scalar.Time `json:"createdAt"`
	UpdatedAt   scalar.Time `json:"updatedAt"`
}

type BlogPostConnection struct {
	Edges    []*BlogPostEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type BlogPostEdge struct {
	Node   *BlogPost     `json:"node"`
	Cursor cursor.Cursor `json:"cursor"`
}

type BlogPostFilter struct {
	Draft      *bool        `json:"draft,omitempty"`
	Tag        *string      `json:"tag,omitempty"`
	Search     *string      `json:"search,omitempty"`
	DateAfter  *scalar.Time `json:"dateAfter,omitempty"`
	DateBefore *scalar.Time `json:"dateBefore,omitempty"`
}

type CreateBlogPostInput struct {
	Slug    string      `json:"slug"`
	Title   string      `json:"title"`
	Excerpt string      `json:"excerpt"`
	Content string      `json:"content"`
	Date    scalar.Time `json:"date"`
	Tags    []string    `json:"tags"`
	Draft   *bool       `json:"draft,omitempty"`
}

type Mutation struct {
}

type MutationResponse struct {
	Success  bool      `json:"success"`
	Message  string    `json:"message"`
	BlogPost *BlogPost `json:"blogPost,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool           `json:"hasNextPage"`
	HasPreviousPage bool           `json:"hasPreviousPage"`
	StartCursor     *cursor.Cursor `json:"startCursor,omitempty"`
	EndCursor       *cursor.Cursor `json:"endCursor,omitempty"`
	TotalCount      int            `json:"totalCount"`
}

type PageInput struct {
	First *int           `json:"first,omitempty"`
	After *cursor.Cursor `json:"after,omitempty"`
}

type Query struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateBlogPostInput struct {
	Slug    string       `json:"slug"`
	Title   *string      `json:"title,omitempty"`
	Excerpt *string      `json:"excerpt,omitempty"`
	Content *string      `json:"content,omitempty"`
	Date    *scalar.Time `json:"date,omitempty"`
	Tags    []string     `json:"tags,omitempty"`
	Draft   *bool        `json:"draft,omitempty"`
}
