name: Deploy to Vercel Staging

on:
  push:
    branches:
      - devel

jobs:
  devel:
    uses: ./.github/workflows/deploy-vercel.yaml

    permissions:
      contents: write
      deployments: write
      pull-requests: write

    with:
      environment: 'devel'
      deployment: true
      production: false
      pr_labels: 'deployed(devel)'
