name: Deploy to Vercel Staging

on:
  push:
    branches:
      - devel

jobs:
  deploy:
    uses: ./.github/workflows/deploy-vercel.yaml
    with:
      environment: 'devel'
      deployment: true
      production: false
      pr_labels: 'deployed(devel)'
